import PublicTemplate from "@/template/public"

export const metadata = {
    title: 'This is my next app',
    description: 'Generated by create next app',
}

const get_items = async () => {
    const result = await fetch('http://localhost:3000/api/item')
    return await result.json()
}

export default async function HomePage() {

    const { data: items } = await get_items()

    return (
        <PublicTemplate>
            {items.map(item => (
                <p key={item.id}>{item.model}</p>
            ))}
        </PublicTemplate>
    )

}