import PublicTemplate from "@/template/public"

import md5 from "md5"

import Image from "next/image"
import Link from "next/link"

export const metadata = {
    title: 'This is my next app',
    description: 'Generated by create next app',
}

const get_items = async () => {
    const result = await fetch('http://localhost:3000/api/item')
    return await result.json()
}

export default async function HomePage() {

    const { data: items } = await get_items()

    return (
        <PublicTemplate>
            <h1 className="mdf-font-normal mdf-mt-0 mdf-pt-xx mdf-mb-0"><b>ADQUIERE</b> TU AUTO YA !</h1>
            <p className="mdf-mt-sm">Encuentra y compra tu auto en menos de 5 minutos.</p>
            <div className="mdf-grid-md mdf-gap-xl mdf-py-xl mdf-mb-xx">
                {items.map(item => ([
                    <Link href={`/item/${item.id}`} key={item.model}>
                        <div className="mdf-b-sm mdf-b-content mdf-rounded-sm">
                            <div className="mdf-flex mdf-flex-justify-between mdf-px-lg mdf-py-md mdf-bg-screen">
                                <p className="mdf-m-0">{item.version}</p>
                                <p className="mdf-m-0">{item.year}</p>
                            </div>
                            <div className="mdf-p-lg">
                                <Image src={`/${item.img_path}`} style={{ width: '100%', height: 'auto' }} alt={item.model} width={875} height={656} />
                                <p className="mdf-my-sm">{item.warranty} años de garantía</p>
                                <p className="mdf-my-sm"><b>$ {item.selling_price}</b></p>
                                <p className="mdf-my-sm">{item.color}</p>
                            </div>
                        </div>
                    </Link>
                ]))}
            </div>
        </PublicTemplate>
    )

}